trigger:
  - master
  - develop

variables:
  buildConfiguration: 'Release'
  sdkVersion: '2.2.300'
  target: Default

pool:
  vmImage: 'windows-latest'
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      packageType: sdk
      version: $(sdkVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Install Cake tool
    inputs:
      command: custom
      custom: tool
      arguments: install -g Cake.Tool --version 0.34.0
  - task: DotNetCoreCLI@2
    displayName: Run build
    inputs:
      command: custom
      custom: cake
      arguments: --settings_skipverification=true --target=$(target)
  - task: PublishPipelineArtifact@1
    displayName: Publish packages artifact
    inputs:
      path: dist/package
      artifact: package
  - task: PublishPipelineArtifact@1
    displayName: Publish build output
    inputs:
      path: dist/build/Spectre.Cli.Extensions.DependencyInjection
      artifact: publish